name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ba6f8d724c7e101c40cac4cdcc7ce787
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
